spring:
  datasource:
    url: "jdbc:h2:mem:intervals"
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    open-in-view: off
logging:
  file:
    name: application.log